### ISSUE TITLE
[Feature Request] Pass optional path to custom css file to stylize prompt window.

### ISSUE THREAD

**Issue by kickthedragon** [p-sam/electron-prompt#17]
I'm considering implementing this into my project.  Let me know if this is of any interest to be added here any i'll make a pull request from my fork once it's finished and tested.

**Comment by p-sam** [comment]
Yes I'm sure some people would like this feature to be implemented. The original scope of the lib was to provide a generic design to ask for values kind of like a system modal, but I can see an interest in making the window go with the host app developed. I'd prefer that this option add the provided css and does not remove the css included in the lib, so that the implementer only has to deal with overrides.
Also be sure to start of develop branch since I can rebase master between tags, but releases tags are safe and untouched.

**Comment by p-sam** [comment]
resolved with #27
