### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by yafp** [p-sam/electron-prompt#52]
I am using 1.4.0 for a dialog in my project where the user can define/input a password.

It would be great to have an object/key for min-length.

Example: 
* i want the password to have at least 8 characters.
* Pressing the OK button should be impossible as long as the input has not reached a length of 8

HTML5 reference:
`<input type=text minlength=10>`

**Comment by p-sam** [comment]
You should be able to feed such properties in `inputAttrs`

**Comment by yafp** [comment]
```
inputAttrs: {
                type: 'password',
                minlength: 10,
```

has no effect

**Comment by p-sam** [comment]
The property is set as intended, but you're expecting some kind of effect from its presence. You won't get any form validation happening simply because:

1. the input is not in a form
2. because of not being in a form, it's also not submitted, the value is only read and then sent via IPC

You probably want to add support for "Form Validation", right ?

**Comment by yafp** [comment]
Hey,
it would be great if the input element attributes would be fully used for validation yes.
But i do understand if that's not on your todo list ;) 

Best regards
yafp

**Comment by p-sam** [comment]
Feel free to reopen this and rename it into form validation or something like that, or create another issue. I haven't got around doing it as I've been mostly focused around Nintendo Switch related projects, I may take a look at it at some point

**Comment by yafp** [comment]
@p-sam 
i am not using this package anymore - therefor i have no more need for that function. As noone else was voting for the issue it seems like it is not really needed ;)

Greetings
