### ISSUE TITLE
Feature Request: allow creating an inescapable prompt

### ISSUE THREAD

**Issue by mooocer** [p-sam/electron-prompt#63]
The available prompt although allows keeping on top, can be hidden with workspace shift and allows interacting on other apps below it. I need to create an inescapable prompt. Some prompts need to be handled right away, which are important and need the user to get it done right away. A basic requirement could be time tracking through logging.

`x-kill` on Ubuntu, for example, opens the following prompt which does not allow changing workspace or clicking elsewhere:

![Screenshot from 2020-08-28 18-56-52](https://user-images.githubusercontent.com/35009811/91614654-8e9dce80-e99f-11ea-9d1b-c55f684216ad.png)

Not sure if it's allowed by OS, but if it could be done it would be very helpful for productivity.

**Comment by p-sam** [comment]
I came back to check on this issue a few times, so I'll probably close it right now. I understand what you're trying to achieve but I can't really implement that in the lib, it's out of scope with what I want it to be (-> more or less a generic replacement to the window.prompt() function in the browser). What apps usually do is prevent focus to their own other windows, not all of them, and that's currently supported and working on all the platforms electron currently runs on.

In order to do what you're trying to do, if it's just for your own usage, you might be able to spawn a dialog using a script and zenity (I never tried to do an inescapable prompt with it though). But you probably already have figured out something since then.
