### ISSUE TITLE
Use `@electron/remote` instead of importing it from `electron` as it will be deprecated in Electron version 14

### ISSUE THREAD

**Issue by kimlimjustin** [p-sam/electron-prompt#76]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

The latest version of Electron, 14 has deprecated the `{remote}` import from the `electron` package and they created another package for it, `@electron/remote`. using `electron.remote` will cause an error saying it's undefined. So, please update it to avoid errors.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/electron-prompt/lib/index.js b/node_modules/electron-prompt/lib/index.js
index 871b75f..c5caf23 100644
--- a/node_modules/electron-prompt/lib/index.js
+++ b/node_modules/electron-prompt/lib/index.js
@@ -1,7 +1,7 @@
 const electron = require('electron');
-
-const BrowserWindow = electron.BrowserWindow || electron.remote.BrowserWindow;
-const ipcMain = electron.ipcMain || electron.remote.ipcMain;
+const remote = require("@electron/remote");
+const BrowserWindow = electron.BrowserWindow || remote.BrowserWindow;
+const ipcMain = electron.ipcMain || remote.ipcMain;
 const url = require('url');
 const path = require('path');
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by p-sam** [comment]
Hi, thanks for the issue, I think that a PR would be more approriate since you already proposed the changes required. So I'd say the right to do for you and for me is that you submit those changes as your contribution via pull request

**Comment by p-sam** [comment]
Reopening because it now crashes when used from the main process

**Comment by p-sam** [comment]
Delving a bit deeper in the subject, I'm realizing this is a much more problematic scenario and I made a mistake in merging this. Using @electron/remote is not a proper replacement to the remote module for our concerns as a lib, we should not force to use specifically this module since it also requires to be inited in the main process, which was not handled in the PR. As the @electron/remote README states, `There is almost always a better way to accomplish your task than using this module`, and so I'll invite anyone that want to use this in a renderer context to either build a 1 line handler using the handle/invoke IPC API or a more obvious and sensible solution which is to do a modal since you're already in a webpage anyway.

I'll be working on reverting the merged PR in some way, reinstating the renderer support that still works for older versions of Electrons, and possibly add a note on that matter in the README, closing the issue

**Comment by p-sam** [comment]
@kimlimjustin Please check that everything works for you using the latest develop commit, it should accomplish what you wanted. While usage from a renderer process was an afterthought added by a contributor, it probably would be a shame to lose the feature altoghether. But I made it so using the remote module would be a not-recommended and deliberate action, in order to push for better usage of IPC, and reduce the overall IPC overhead present in electron apps due to the overall laziness of the ecosystem. I'll probably push a release shortly after

**Comment by kimlimjustin** [comment]
Yes, it works! Tysm!
